### ISSUE TITLE
React.render() Deprecated

### ISSUE THREAD

**Issue by AustinMCrane** [christianalfoni/flux-react-boilerplate#12]
When running the project i get two of the following errors/warnings:

![screen shot 2016-02-18 at 8 04 58 am](https://cloud.githubusercontent.com/assets/12687588/13145454/665ccfc6-d616-11e5-82b4-42c6c7766ae9.png)

I believe it is referencing this section of code in the main.js, keep in mind i didn't make any changes to the project.

![screen shot 2016-02-18 at 8 05 56 am](https://cloud.githubusercontent.com/assets/12687588/13145472/8b4640f6-d616-11e5-8942-d547c5052fd1.png)

**Comment by AustinMCrane** [comment]
I may try to fix this and issue a pull request if that is acceptable? Thank you for creating this project. It is very helpful but just needs some updating.

**Comment by christianalfoni** [comment]
If you could make an update that would be great, I will happily pull it in :) Glad you like it!
