### ISSUE TITLE
Missing dispatcher

### ISSUE THREAD

**Issue by davidevernizzi** [christianalfoni/flux-react-boilerplate#4]
Am I wrong or you are missing the dispatcher here? If you look at original facebook repo, they have a dispatcher:

https://github.com/facebook/flux/blob/master/examples/flux-todomvc/js/dispatcher/AppDispatcher.js

Did you leave it out on purpose?

**Comment by christianalfoni** [comment]
Hi @davidevernizzi!

Yup, it was removed on purpose. When I started out with flux the dispatcher was just passing a long actions so I decided to make the actions able to dispatch themselves by using events. It just reduces syntax and makes more sense to me. It is better that a store listens for specific actions than all actions being dispatched to all stores and you have to use a switch statement to figure out if the store should act upon the action or not.

Some developers also highlights "action creators" as an important part of flux. An action creator will handle async stuff, like HTTP requests and the only thing that is dispatched to stores are actual state changes and values. No async behavior in the stores. Personally I have no negative experience with async behavior in stores.

Please let me know if you have any more questions :-)

**Comment by davidevernizzi** [comment]
@christianalfoni, I agree that without the dispatcher syntax is much clearer, but I think that the dispatcher is a key component to make things modular and to allow synchronous actions. Give a look at this page, it explains quite clearly all these things: http://www.toptal.com/front-end/simple-data-flow-in-react-applications-using-flux-and-backbone

**Comment by christianalfoni** [comment]
Hi again @davidevernizzi!

Thanks for the link, I still have lots to learn on flux so this will definitely help :-) Btw, check out this lib: https://github.com/Yomguithereal/baobab#cursors , very interesting way of handling the whole application state as a one traversable tree. Pretty cool :-)
